[package]
name = "neu-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {features = ["derive"], version = "4.3.0"}
postgres = "0.19.5"
