-- Add migration script here
CREATE TABLE IF NOT EXISTS identification (
	id UUID NOT NULL PRIMARY KEY,
	identification_slug TEXT NOT NULL UNIQUE,
	name TEXT NOT NULL UNIQUE,
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);