-- Add migration script here
CREATE TYPE services_type AS ENUM ('HAIR', 'NAILS', 'MAKEUP', 'MASSAGE', 'FACIALS', 'WAXING', 'BARBERSHOP', 'SPA', 'TATTOO', 'GELE TYING');

CREATE TABLE IF NOT EXISTS services (
	id SERIAL PRIMARY KEY,
	name services_type NOT NULL UNIQUE,
	services_slug TEXT NOT NULL UNIQUE,
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);