application:
  port: 8000
  host: 0.0.0.0
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "neudb"
config:
  jwt_secret: "my secret strings"
  jwt_expires_in: "60m"
  jwt_maxage: "60"